name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  test:
    steps:
      - name: premakumari.sathiamurthy@straive.com
        run: echo "Hello, world!"
      

